vlans:
  - vlan_id: 999
    name: Native
    state: present
  - vlan_id: 2012
    name: BR1 <-> BR2
    state: present
  - vlan_id: 2018
    name: BR1 <-> ISP1
    state: present
  - vlan_id: 2019
    name: BR2 <-> ISP1
    state: present
  - vlan_id: 2028
    name: BR1 <-> ISP2
    state: present
  - vlan_id: 2029
    name: BR2 <-> ISP2
    state: present

interfaces:
  - name: Ethernet1/0
    mode: trunk
    trunk_allowed_vlans: 2012,2018,2019,2028,2029
    native_vlan: 999
  - name: Ethernet1/1
    mode: trunk
    trunk_allowed_vlans: 2012,2018,2019,2028,2029
    native_vlan: 999
  - name: Ethernet1/2
    mode: trunk
    trunk_allowed_vlans: 2012,2018,2019,2028,2029
    native_vlan: 999
  - name: Ethernet1/3
    mode: trunk
    trunk_allowed_vlans: 2012,2018,2019,2028,2029
    native_vlan: 999
