---

- name: Debugging jinja
  gather_facts: no
  hosts: localhost
  vars:
    vrfs:
      - name: CLIENT
        rd: "1:1"
        rt: "1:1"
      - name: MGMT

  tasks:
    - name: Generate configs
      template:
        src: PE.j2
        dest: result.cfg

