---
defaults:
  username: admin
  password: admin
  platform: cisco_ios

dynamic:
advanced-dot1x__01:
advanced-dot1x__02:


pod-gear:
  pod: unallocated

infra:


pod-routers:
  groups:
    - pod-gear
  tags:
    - router


pod-switches:
  groups:
    - pod-gear
  tags:
    - switch


matrix-switches:
  dot1q_tunnel_vlan_start: 2000
  groups:
    - infra

pair-routers:
  groups:
    - infra

pod-mgmt:
  groups:
    - infra