---
runners:
  plugin: threaded
  options:
    num_workers: 10

logging:
  enabled: False

inventory:
  plugin: SimpleInventory
  options:
    host_file: "inventory/hosts.yaml"
    group_file: "inventory/groups.yaml"
    defaults_file: "inventory/defaults.yaml"
