- name: Reset configuration of pod gear to bootstrap
  ios_command:
    commands:
      - configure replace nvram:startup-config force


- name: Wait for 5 seconds
  wait_for:
    timeout: 5


- name: Configure pod gear according to the lab template config
  ios_config:
    src: "user-data/topologies/{{ lab_template }}/configs/{{ lab_hostname }}.txt"


- name: Save current lab config to the flash
  ios_command:
    commands:
      - "copy running-config unix:lab-config\n\n\n"
