---
runners:
  # plugin: serial
  plugin: threaded
  options:
    num_workers: 10

core:
  raise_on_error: True

logging:
  enabled: False

inventory:
  plugin: SimpleInventory
  options:
    host_file: "inventories/10-csr-local/hosts.yaml"
    group_file: "inventories/10-csr-local/groups.yaml"
    defaults_file: "inventories/10-csr-local/defaults.yaml"