---
all:
  vars:
    username: admin
    password: admin
    ansible_connection: local
    ansible_python_interpreter: "/usr/bin/env python"
  children:
    sjc:
      hosts:
        SJ-R1:
          ansible_host: 192.168.122.11
        SJ-R2:
          ansible_host: 192.168.122.12
        SJ-SW1:
          ansible_host: 192.168.122.13
        SJ-SW2:
          ansible_host: 192.168.122.14
        SJ-HUB1:
          ansible_host: 192.168.122.15
    bru:
      hosts:
        192.168.122.20:
